### ISSUE TITLE
김종윤

### ISSUE THREAD

**Issue by nuitciel99** [cccr-pass1/project_backend#1]
오늘 한 일.

1. front style 에러 해결 및 커밋
2. backend gradle build 에러 해결
3. gradle build를 Dockerfile로 이미지 및 컨테이너화
4. Docker Hub에 이미지 올리기

내일 할 일.

1. EC2에서 위에서 한거 해보기
2. 남현씨 front 이미지랑 연동되는지 확인
3. Git Action

**Comment by chosam2** [comment]
배포해드린 EC2 서버에 Docker 설치해두었습니다. 종윤님/남현  프론트 / 백엔드 앱 서로 연결되는지 테스트 해보고 오후에 알려주세요.

**Comment by nuitciel99** [comment]
오늘 한 일.
1. EC2에서 docker image & container 구축
2. front 서포트 

내일 할 일. 
1. 남현씨랑 slack 생성
2. Backend Git Action
